### PR TITLE
optimizations

### PR DESCRIPTION
**Pull request by novacrazy**
Removed array splice in favor of an offset value and preallocate the sorted results array.

I'm not entirely sure if this works, but all the tests pass. I added a test that should break it if it didn't work, and even that passes, so I'm going to go ahead and open this PR.

### CODE REVIEW

**Comment by novacrazy** [comment]
CC @gustavohenke, got any thoughts on if this works?

**Comment by gustavohenke** [comment]
It seems to me that it'll work.

But I need to ask you: are you having performance problems? I think the code got messier with that `offset` variable.

**Comment by novacrazy** [comment]
I have an addiction to performance. Heh. Simple as that.

**Comment by novacrazy** [comment]
Even with JavaScript, a language not particularly known for high performance, I sometimes drop down to looking at the assembly the V8 JIT produces to look for more places I can improve upon. 

But using an integer offset, reducing memory allocation and array modifications, and even reducing the number of closures in a particular scope can significantly improve performance in many cases.

However, I wasn't sure if this actually worked because of how the recursion worked out and if splice ever did anything but shift the first element off the nodes array.

**Comment by novacrazy** [comment]
Upon inspecting the value of `index`, it does always seem to be zero in the splice version.

**Comment by gustavohenke** [comment]
Okay then. Do you have some benchmarks? I'm curious to see some numbers :)

**Comment by novacrazy** [comment]
I'll throw some together really quick. I'll push them to this branch.

**Comment by novacrazy** [comment]
Here are the benchmarks I just ran.

| Description | Library | Op/s | % |
| --- | --- | --: | --: |
| simple dependency chains | old version | 28,818.96 | 14% |
|  | new version | 211,578.12 | 100% |

Pretty crazy, huh?

**Comment by gustavohenke** [comment]
"old version" is the current version published to npm? Or is it gustavohenke/toposort#12?

**Comment by novacrazy** [comment]
Old version is the 0.3.1 version published to NPM. I just copied it from there for the benchmark. I can run a separate benchmark for the splice vs offset on the new version if you'd like, though?

**Comment by gustavohenke** [comment]
Not needed. LGTM.

**Pull request merged**
